---

- name: "Basic Packages to install Debian"
  apt:
    update_cache: yes
    name: '{{ debian_local_packages }}'
    state: latest
  when: ansible_os_family == "Debian"

  - name: "Basic Packages to install RedHat"
  apt:
    update_cache: yes
    name: '{{ redhat_local_packages }}'
    state: latest
  when: ansible_os_family == "RedHat"
