---
- name: "Restart Docker"
  ansible.builtin.systemd:
    name: "docker"
    state: "restarted"
    enabled: true

- name: "Restart Nomad"
  ansible.builtin.systemd:
    name: "nomad"
    state: "restarted"
    enabled: true

- name: "Restart Consul"
  ansible.builtin.systemd:
    name: "consul"
    state: "restarted"
    enabled: true
