---

- name: "Kill banned services"
  shell: "pkill -f {{ item }}"
  with_items: "{{ banned_services }}"
  ignore_errors: yes
  changed_when: False
  failed_when: False

- name: "Packages to remove DEB based"
  apt: 
    name: '{{ debian_purge_packages }}'
    state: absent
    purge: yes
    autoremove: true
  when: ansible_os_family == "Debian"

- name: "Packages to remove RPM based"
  yum: 
    name: '{{ redhat_purge_packages }}'
    state: absent
  when: ansible_os_family == "RedHat"
