become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38616566636132386135393930623637303337363139333064613937363735643032363066383633
          6365623639363261633037353965633235623866643063310a636439623064623439636465643764
          66366433363033376436616662626363303739366636363738333530383761313534633139336534
          3730633934643862350a653263326237633333613363636562356262633231613466653933613939
          6630

gnome_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38316539633862333633303932643432373634366237326634373961316461333232363034313733
          6532643461363932333933393066383830366432353665340a386363646166303531363865373733
          63363761616337666532363334623666333461313633383164613465306164653761333239373439
          3532336464323162630a353666326634636339623135643134643139653232363135366538313364
          3439

ssh_ca: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDnHmAo1KLbf2QWCgaFII4ZmnL8sJ12WzAnjjY76rjk5OfU+hvMvGtwWcN3KywiJ+26Rt63bLhVrFdtdeoRuP3S+xc3p+6lJBnCuc0/bwYdDtUamNuNKxZxiOdO08psTQyZdvZ1uiWlo0wPYI1uZ5fTr3us1Y4c4UWWtj7V4sDyhKBB/P4KETYf8adnrZu9xuGTHaoeipEIWaI9jIgtD54b1szwZJ0IxbmMjS/pPSm8SQ/A9GLMFkD/FqmuSulO66fT5j8Exuk9FAnSB8AiF3O6Q/vQrEVKAANDFiGRCdSF2ZmmRQq6BXsWXo0D66piDNHIIKcerdSMgSiZ4AwOUg0n2GgiznCWSE2ST2hPBJxvc9Rbs0ReDB8faQrUtGjupeaUpWl5iHMnVIgMgD1EeJNcUc0SSfHrkVILsYHv+g9AzQmDDfeRimsxi7mFU2hAbHXGaDPu1HFaUbVPxNsdhKnVRHbsDhafCFNDJdS960bpUjpvfCMcQQN9RFwwFPdSfGDAsuxHuMSpVk1t4ABSEWowvvhZ/oO8Pyff2FiHmLAgfQl5REyZUxfc915ysiYBx348fC4P3SFs3nDCwSbTRRF50UULUOnf6zh8bfAPummxnIySIrboq7zeWIB03pM+Wt9Xm2Uojxj2Q2fIo0dWRV6lmIQ/Bfw33R1MA02R+aGx/Q=="
