---

ROOT_PW: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34363132393864653263633234613239393661353632316335383932306330323030623539393266
          6631373766373233383031393964623333366632656437640a326662353761323161666434333164
          35643336303263623862663238326637353538333030376431306335376133626634633565306631
          6231323861383466380a303065633130383965633334356563313962383236643363336238663561
          38343430633861326334336162323631393934353163613433343038666563613862356130316166
          3061393162333262613035356239366161316533616335383365

MYSQL_PW: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32303261353935633362636135306434333664656165393834333531363262613938646338343462
          3931313634363666663936333234663361663736636332330a343466613231306234626238663964
          36346537323934366264306235643937666464653461636134346361383437326161613933353235
          6563393061616362330a636532303962656330616635613935303431333730613331393436356366
          38633330363836633262306563303730633163323261663039376431303861323632366636646664
          6432663637393837643461323730333734653831626233616639
