---
nomad_version: "1.10.0"
consul_version: "1.20.5"

nomad_datacenter: "iron"
consul_datacenter: "iron"

nomad_retry_join:
  - "192.168.1.86"
  - "192.168.1.35"
  - "192.168.1.169"

consul_retry_join:
  - "192.168.1.86"
  - "192.168.1.35"
  - "192.168.1.169"

