---

- name: "Install required packages"
  import_tasks: packages.yml

- name: "Debian configure Apache HTTP Webserver"
  import_tasks: apache2.yml
  when: ansible_os_family == "Debian"

- name: "Setup unattended upgrades"
  import_tasks: unattended-upgrades.yml
  when: ansible_os_family == "Debian"
